### ISSUE TITLE
Synchronization does not work

### ISSUE THREAD

**Issue by andresadanmx** [dualcube/moowoodle#1]
Hey guys, first thank you very much for this great contribution.

Synchronization does not work, I configured the plugin in WordPress/Moodle according to the tutorial, but for some reason courses do not appear in WooCommerce.

I have installed:
Wordpress version 4.3
woocommerce 2.4.6
Moodle 2.9.1

See the following screenshots:
http://prntscr.com/8a55a3
http://prntscr.com/8a554r

Any help? Thanks.

**Comment by sumandualcube** [comment]
Fixed.

**Comment by olmmoreno** [comment]
Hi, I have the same issue, can you help me?
