### ISSUE TITLE
Users are created with administrator data!

### ISSUE THREAD

**Issue by sumandualcube** [dualcube/moowoodle#11]
when I do a purchase on my website it sends the email with the login data to moodle but when I click on the link it pushes the admin configuration

**Comment by trideepdm** [comment]
Thank you, this issue will be fixed on our next update.

**Comment by tuansaharizam** [comment]
Moodle already updated to version 3.9. When will be your next update?

**Comment by sumandualcube** [comment]
Please use the latest MooWoodle from https://wordpress.org/plugins/moowoodle/
and MooWoodle enrolment from https://dualcube.com/shop/

Thank you.
