### ISSUE TITLE
User sync failing

### ISSUE THREAD

**Issue by reza-jalaei** [dualcube/moowoodle#112]
User sync is failing due to commented out 'get_users_data' method in ExternalService.php

The error resulted from an attempt to sync is "Unable to fetch users." which comes from MooWoodle Pro's Cron.php attempting to make a request for that method under "MooWoodle()->external_service->do_request( 'get_users_data'..." 

This is with MooWoodle Pro and Auth MooWoodle installed. 

Commenting out the 2 lines in ExternalService.php resolved the issue.

**Comment by moumitahalder** [comment]
Hi @reza-jalaei, thanks for reaching out to us.

In our latest version, we've already commented out those two lines. Please ensure you're using the latest version on your end.

**Comment by reza-jalaei** [comment]
Hello @moumitahalder, 

The issue is that they're commented out! Yes I'm using the latest version of MooWoodle, MooWoodle Pro, and Auth MooWoodle (installed on Moodle). 

Syncing users from Moodle to WordPress was resulting in "Unable to fetch users." in the logs until I uncommented those lines.

**Comment by moumitahalder** [comment]
Thanks for explaining this. Yes, currently you need to uncomment those line.
However we will add a filter in our next update to fix this.

**Comment by reza-jalaei** [comment]
Thanks @moumitahalder 

I have another question, I'm running the Moodle to Wordpress sync right now and it seems to be stuck on 'Current end_user_id: 7' (I added some logging to check the user id in the loop over the data from Moodle in Cron.php)

We have close to 8000 users and it's been on 7 for the past 2 hours, any ideas what could be causing this? 

Do you have any recommendations on how to handle this first batch since it's so large? Could I maybe dump the user data from Moodle and import them to WordPress MySQL directly? 

Thanks!

**Comment by moumitahalder** [comment]
@reza-jalaei, in that case please use some plugin like Crontrol and pause this cron for now. 

Then re-run this cron again. Let us know if this works.

**Comment by reza-jalaei** [comment]
For some reason a second try also got stuck at 7 so I decided to use the API MooWoodle Auth exposes from the Moodle side to fetch all the users and convert the JSON to a MySQL query and bulk import the 9000 users. 

It's still running, after that I will enable real-time sync as that seems to be working well.

**Comment by moumitahalder** [comment]
Hi @reza-jalaei , we are hoping that the issue got fix. 
If you need any further help, do open another thread.
