### ISSUE TITLE
Unable to install plugin on Moodle

### ISSUE THREAD

**Issue by Idigoras** [dualcube/moowoodle#12]
Hi,

I'm running Moodle 3.7.1+ (Build: 20190725) and when I upload de zip (directly downloaded from this page) first I get the error that Moodle can't detect what type of plugin it is. I have to select the type from a dropdown, so I chose "Module (mod)".

After that it starts to install, but I get an error: 

> Validating mod_moowoodle ... Error
  [Error] File version.php not found [null] 
Instalation aborted due to a validation error

I've been looking and no one seems to have this problem, I guess I'm doing something wrong.

**Comment by Lior79** [comment]
Hi,
The moowoodle plugin is not intended to be installed in moodle but in wordpress (under woocommerce).
There is another plugin for moodle: moowoodle-moodle-dhb1sz which can be downloaded here:
https://dualcube.com/product/moowoodle-enrolment/
