### ISSUE TITLE
Users are not being created

### ISSUE THREAD

**Issue by mathiasribeiro** [dualcube/moowoodle#18]
I did the integration a few days ago following the guidelines. In the end, courses are properly synchronized but users are not being created.

**Comment by purnendudash** [comment]
Are you talking about the users created on moodle?

Means enrollment function is not working?

Kindly confirm.

**Comment by mathiasribeiro** [comment]
Yes, the courses are synchronized like products, but when a purchase is made, the use receive a e-mail with the logins informations, but in moodle the user don't exist. The plugin isn't creating users in moodle.

**Comment by mathiasribeiro** [comment]
I am using moodle 3.10 version and the last version of the wordpress and woocommerce.

**Comment by purnendudash** [comment]
Would request you to check our latest beta - https://wordpress.org/support/topic/new-beta-version-released/

**Comment by PatrikCoder** [comment]
Have installed the last version of woomoodle, Moodle 3.9.15 and the actual Wordpress core and Woocommerce release. Same issue with correct synchronized courses in Woocommerce, but no course and login credentials are shown in my accost-dashboard under my courses.
