### ISSUE TITLE
Use of experimental xml-rpc feature

### ISSUE THREAD

**Issue by lukecarbis** [dualcube/moowoodle#2]
```
Fatal error: Call to undefined function xmlrpc_encode_request() in /srv/www/wordpress-develop/src/wp-content/plugins/moowoodle/includes/dc-woodle-core-functions.php on line 114
```

From http://php.net/manual/en/function.xmlrpc-encode-request.php:

> **Warning** This function is EXPERIMENTAL. The behaviour of this function, its name, and surrounding documentation may change without notice in a future release of PHP. This function should be used at your own risk.

Not all hosts support xml-rpc, there should be an alternative implementation.

**Comment by lukecarbis** [comment]
My suggestion is to use Moodle's REST Protocol, instead of its XML-RPC protocol.

**Comment by sumandualcube** [comment]
Fixed.
