### ISSUE TITLE
Missing Cohort and Group ID on Wordpress / Woocommerce / Product: Moodle Linked Course Section

### ISSUE THREAD

**Issue by luisurbinanet** [dualcube/moowoodle#28]
Hi
I'm haven a issue on my Wordpress Site on:
Wordpress / Woocommerce / Product: Moodle Linked Course Section 
and it's that I can't see the Cohort ID and Group ID information as you show in your docs page: https://dualcube.com/docs/moowoodle-set-up-guide/#1-toc-title on the section To Setup products: WooCommerce > Products > Course Name 

I can see Moodle Linked Course Section with a Select list with my Courses Sync and this is good but I needs assign a Cohort for my students on this specific case for this Woocommerce Product because I don't want to duplicate the course for every different case.

Versions:
- Wordpress:                                        5.6.2
- Moodle:                                             3.9.3
- MooWoodle Wordpress PlugIn:          3.0
- MooWoodle Moodle PlugIn:               2.1         2021010900

I can do the proper modifications where you suggest that I make. I'm ready to hear you. Thanks

**Comment by Scott-Rogers2020** [comment]
Any response received to this? or did you manage to resolve it? I have the same issue.

Cheers Scott

**Comment by moumitahalder** [comment]
Hi, not to worry. 

We have removed the Cohort ID and Group ID concept from MooWoodle configuration.

**Comment by Scott-Rogers2020** [comment]
Hi @moumitahalder,  this response is about 2.5 years late. I have a question though and hopefully you can answer before another 2 years goes by. Why would you make the enrolment feature less functional? Of course people want to enrol in groups and cohorts. The plugin just became less useful. 

Maybe you can explain the logic in remove useful features.


Cheers Scott
