### ISSUE TITLE
E-mail - New Moodle Enrollment 

### ISSUE THREAD

**Issue by 3WTECNOLOGIA** [dualcube/moowoodle#33]
the email with the subscription link in moodle is only sent if the wordpress language is in english.

If I leave the Brazilian Portuguese language, the email is not sent.

How do I fix it?

**Comment by moumitahalder** [comment]
Hi @3WTECNOLOGIA, may I know what is the default language of your site? 

Also, have you translated the plugin into Portuguese? If not, please do use plugins like the Loco plugin and follow this guide to translate the strings : https://wc-marketplace.com/knowledgebase/wcmp-translation-guide/

**Comment by 3WTECNOLOGIA** [comment]
> Hi @3WTECNOLOGIA, may I know what is the default language of your site?
> 
> Also, have you translated the plugin into Portuguese? If not, please do use plugins like the Loco plugin and follow this guide to translate the strings : https://wc-marketplace.com/knowledgebase/wcmp-translation-guide/

Hi,

The website's default language is Portuguese-Brazil.

On a test site, I translated the site with plugin! I had to leave the default language in English to work sending the email.

**Comment by Valdesquadra** [comment]
Olá @3WTECNOLOGIA eu resolvi adicionando este trecho de código no functions.php do tema:

unction moowoodle_force_set_language($user_data){
$user_data['lang']='pt_br';
return $user_data;
}
add_filter('moowoodle_moodle_users_data', 'moowoodle_force_set_language' );

Vi isso numa thread no fórum de não suporte do plugin no Wordpress.org. Espero que ajude
