### ISSUE TITLE
My Courses empty

### ISSUE THREAD

**Issue by natas123** [dualcube/moowoodle#46]
Hello
I am testing the plugins and everything works correctly only something strange happens to me, with a test user I have bought two courses everything works correctly, he sends me the email and I can access moodle but in wordpress I go to the "My courses" tab and this empty does not show me the two courses with the link to see them. What could be the problem?

Wordpress - 5.9.3
Moodle 3.11.6+

Greetings and thank you

**Comment by moumitahalder** [comment]
Hi @natas123 as you can see we didn't face any such issue https://prnt.sc/0c_6r0Q2Acf6

Can you please update MooWoodle to the latest version and check again.
