### ISSUE TITLE
User creation failed while course order is complete

### ISSUE THREAD

**Issue by vijai1996** [dualcube/moowoodle#79]
WP version: 6.4.2
Plugin version: 3.1.5
moodle version: 4.3

Everytime I order for course is completed, moowoodle tries to create a user but it fails everytime with the below log:
`moowoodle response:{"headers":{},"body":"{\"exception\":\"invalid_parameter_exception\",\"errorcode\":\"invalidparameter\",\"message\":\"Invalid parameter value detected\"}","response":{"code":200,"message":"OK"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}`

**Comment by kndnsow** [comment]
Hey @vijai1996 ,
Thanks for reaching out to us. 
Kindly turn on the Advance Log option from MooWoodle>>settings>>General.
And run the Test Concoction then place an order for a new user.
After that share the log file with us. 
So that we can look into the issue and help you accordingly to  solve it.
