### ISSUE TITLE
upgrading WP and Moodle dosent create users automatically

### ISSUE THREAD

**Issue by cristianmenghi** [dualcube/moowoodle#8]
Hi, wp is up-to-date, Im update moodle to last stable version, all the settings are ok, MooWoodle is installed and configure in moodle, but still get this message in wp "This plugin needs to be installed on your Moodle site after installing this MooWoodle plugin to enable the course enrolment feature.– Click here"  and users auto creation and enroll in moodle stop working.

Any idea?

Thanks.

**Comment by tuansaharizam** [comment]
Face the same problem

**Comment by sumandualcube** [comment]
Dear user,

All the fixes were made on our latest plugins on WordPress (MooWoodle) as well as MooWoodle enrolment (dualcube).

Thank you.

**Comment by tuansaharizam** [comment]
Still same problem, downloaded latest release and followed all steps.
When checked with WordPress, found out that REST API problem. 
How to fix?
