### ISSUE TITLE
User Enrollment not working properly for manually created products

### ISSUE THREAD

**Issue by moumitahalder** [dualcube/moowoodle#83]
** Recreate the issue**
- Sync the courses from moodle to wordpress
- Goto Add Product  >> link any moodle course.

As a customer purchase this course, however enrollment mail and process is not taking place. 

**Reason**
The linked course id is added however moodle_course_id not net added with this product

**Comment by lsthompson** [comment]
This is fixed now, right?

**Comment by moumitahalder** [comment]
Hi, this issue is already fixed in our last update also.
