### ISSUE TITLE
website documentation is a pure garbage

### ISSUE THREAD

**Issue by ghost** [dualcube/moowoodle#86]
I've also told this at the facebook community, but dualcube wants to sell pure trash.
the documentation is unclear about if we must, or must not install the moowoodle connector on moodle instance. and if we must, why it is not in the website anymore. some permissions in the grant roles for the api key are not in the system
we want a real, real, real step by step instructions.
also, the debug logs in moowoodle woocommerce is not clear as well.
it says permission errors in the logs. just this? what is this for?
it should be showing us error codes, error based in curl http, or something extremaely extremely detailed so we will be able to debug it.
also, the plugin has a real poor documentation all along. a lot of steps were missing

**Comment by moumitahalder** [comment]
@thadeu220 , Thank you for bringing your concerns to our attention.

We apologize for any confusion you've experienced with our MooWoodle plugin. 

We have updated the documentation, we are hoping this is now quite cleat for you to understand how to proceed step by step : 

- **Plugin Installation** : https://dualcube.com/docs/moowoodle-free-pro-plugin-installation/
- **MooWoodle Set up guide**  : https://dualcube.com/docs/moowoodle-set-up-guide/
- **MooWoodle Pro Set up guide** : https://dualcube.com/docs/moowoodle-pro/
- **MooWoodle Moodle Set up guide** : https://dualcube.com/docs/moowoodle-moodle-connector/


If you believe there are improvements needed to enhance clarity for our users, please share your suggestions with us. 

Regarding the error log, we've conveyed your feedback to our developers to ensure greater clarity so our users can understand what to look for.

**Comment by ghost** [comment]
wow, the documentation seems to be pretty much better now. now it specifies
all steps, in full step. with no more omitted steps.
another idea, is to enable the enable advanced logs checkbox as an system
ui checkbox. this would enhance the accessibility a lot. for now, it is a
javascript toggle that cannot be clicked using screen readers.
i will try to setup and i let you guys knwon

Em seg., 12 de fev. de 2024 às 04:38, moumitahalder <
***@***.***> escreveu:

**Comment by moumitahalder** [comment]
Thank you for your feedback! 

I am afraid, we can't modify the UI for the advanced log, as the current format aligns with our interface design. Could you kindly clarify why there's a need to click this checkbox using screen readers? Please note that this checkbox typically requires activation only once.

**Comment by ghost** [comment]
wow, in fact all checkboxes should be in the system UI format due to
accessibilit purposes. sometimes i must install moowoodle in a client
website.
but howcome i will do that, if i need to have a sighted person to do it.
this is accessibility standard.
the checkboxes in all toggleable options should work the same way to
accessibility

Em ter., 13 de fev. de 2024 às 04:16, moumitahalder <
***@***.***> escreveu:
