### ISSUE TITLE
moowoodle error:Invalid token - token not found

### ISSUE THREAD

**Issue by coffseducation** [dualcube/moowoodle#92]
I have followed instructions but get:

moowoodle error:Invalid token - token not found

nb. There is no setting
In this page, enable the “MooWoodle Connect” Settings
Is that required and how to install whatever is necessary?

**Comment by moumitahalder** [comment]
Hi @coffseducation, thanks for getting in touch with us.

The invalid token was an issue with your token generation. 
Please follow this document https://dualcube.com/docs/moowoodle-set-up-guide/#7-toc-title

Once the token is created then check the Test Connection again. 

Please note, you only need to configure MooWoodle plugin. There is no need to configure any other plugins.

**Comment by coffseducation** [comment]
Thanks for the reply @moumitahalder .
I re-read the documentation twice and still could not find anything missing in my setup.
I then removed the https. This did not work. I re-added the https. Test connection now worked! 🤷‍♂️
SOLVED.
