### ISSUE TITLE
Final Test

### ISSUE THREAD

**Issue by moumitahalder** [dualcube/moowoodle#99]
- [x] The pro pop up is not working under "user"" : https://www.awesomescreenshot.com/video/27877896?key=d5d7502012b3c896ea0df9e258024be2
- [x] By default it should be enabled in Pro 
![image](https://github.com/dualcube/moowoodle/assets/28754174/ba814f7c-d202-460c-a405-da603e726aac)

- [x] Product is not getting created by default 
![image](https://github.com/dualcube/moowoodle/assets/28754174/e6317561-745c-4baf-967a-16c3525c821d)

- [ ] create search field for this 
![image](https://github.com/dualcube/moowoodle/assets/28754174/9be9f62e-696e-4127-ace3-4b40887e223c)

- [x] No Course design @Bishal221 

![image](https://github.com/dualcube/moowoodle/assets/28754174/62b68470-0c27-4853-8d4e-4821c5004397)

- [x] the order is on hold, still showing that user is enrolled 
![Uploading image.png…]()

- [x] Error with Enrollment Mail , Subject line missing
Warning: include(C:\xampp\htdocs\moowoodle\wp-content\plugins\woocommerce/templates/emails/new-enrollment.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\moowoodle\wp-content\plugins\woocommerce\includes\wc-core-functions.php on line 345

Warning: include(): Failed opening 'C:\xampp\htdocs\moowoodle\wp-content\plugins\woocommerce/templates/emails/new-enrollment.php' for inclusion (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\moowoodle\wp-content\plugins\woocommerce\includes\wc-core-functions.php on line 345

- [x] Show All Test Done

**Comment by PravatSah00** [comment]
solved
